#!/bin/dash
# open RPGM MV games using nwjs
[ -z $1 ] && printf 'provide a dir name' && exit 1
[ -e "$(whereis nw | cut -d' ' -f2)" ] && cd "$1" && dash -c nw& > /dev/null && cd .. || printf "install nwjs"

exit 0
